---
- name: Change owner of /mnt/data
  become: yes
  file:
    path: /mnt/data
    owner: elastic
    group: elastic
    mode: 0700
    state: directory

- name: Change owner and permissions of /mnt/data/elastic
  become: yes
  file:
    path: /mnt/data/elastic
    state: directory
    owner: elastic
    group: elastic
    mode: 0700

- name: Change owner and permissions of /mnt/data/docker
  become: yes
  file:
    path: /mnt/data/docker
    state: directory
    owner: elastic
    group: elastic
    mode: 0700
