---
- name: Modify GRUB_CMDLINE_LINUX
  become: yes
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=\"[^\"]*)(\".*)'
    line: '\1 cgroup_enable=memory swapaccount=1 cgroup.memory=nokmem\2'

- name: Run bootloader update
  become: yes
  command: "{{ bootloader_update_command }}"