---
- name: Remove docker
  become: yes
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: disable SELinux
  become: yes
  become_user: root
  selinux:
    state: disabled

- name: Add Docker GPG Key
  become: yes
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  when: docker_version == '18.09'

- name: Add docker repository
  become: yes
  yum_repository:
    name: "{{ docker_version_map[docker_version]['name'] }}"
    description: "Docker repository"
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    enabled: yes
    gpgcheck: no
  when: docker_version == '18.09'
  register: repo_installed
  retries: 10
  delay: 30
  until: repo_installed is success

- name: Add RHEL7 Extras repository
  become: yes
  shell: yum-config-manager --enable "{{ docker_version_map[docker_version]['repo'] }}"
  register: repo_installed
  retries: 10
  delay: 30
  until: repo_installed is success 

- name: Install docker
  become: yes
  package:
    name: "{{ docker_version_map[docker_version]['package'] }}"
    state: present

- name: Verify that fs.may_detach_mounts is enabled
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^fs.may_detach_mounts'
    line: 'fs.may_detach_mounts = 1'
    create: yes
